script: make test-app-ci
deploy:
  provider: heroku
  api_key:
    secure: FZy7W9PBHwzbRepJzzYO99gnQEqaCLl7lniTutINfZwwILI/J+y+zVWijqjIGpS6/RUFJUa44iUvvN4G2/6AQ9rMPpFdvDz2t+XGMn7lqY70wkjbGAhPPDTZZqkdGQcNGT3YlzH15h5TJkngZkHU41reYK0Eyoip0cU6BKp+RI8=
  app: akatsuki-presentation-func01
  on:
    repo: arrancar-technology/akatsuki-presentation
    branch: develop
